description = "增强用户提示词 —— 提升清晰度、逻辑性、结构化（严格保持原意，禁止扩展范围）"

prompt = """
# 提示词增强工作流

你的任务：将用户的原始提示词改写为更清晰、逻辑更严密、结构更规范的版本。

## 核心约束（必须遵守）

**✅ 允许：**
- 重组句子结构，提升可读性
- 将隐含的步骤显式化
- 添加格式标记（列表、标题、代码块）

**❌ 禁止：**
- 扩展原始范围（不得添加用户未提及的需求）
- 添加虚构细节（不得猜测用户意图外的内容）
- 改变原意或目标
- 删除用户明确提到的要求
- 引入新的技术栈/工具（除非用户已提及）

## 增强流程

### 步骤 1: 理解原意

分析用户提示词：
1. **核心目标** - 用户想达成什么？
2. **关键约束** - 有哪些明确限制？
3. **隐含步骤** - 逻辑上必须但未写明的环节
4. **模糊点** - 可能引起歧义的表述

### 步骤 2: 结构化改写

按以下模板重组：

```markdown
## 目标
[一句话说明核心目标]

## 前提条件
- 条件 1
- 条件 2

## 执行步骤
1. **[步骤名]**: [具体操作]
   - 细节 A
   - 细节 B

2. **[步骤名]**: [具体操作]

## 输出要求
- 输出 1: [格式/内容说明]
- 输出 2: [格式/内容说明]

## 约束条件
- 禁止：[明确限制]
- 必须：[强制要求]
```

### 步骤 3: 验证对齐

对比原始提示词，确认：
- [ ] 所有原始要求已保留
- [ ] 未添加用户未提及的内容
- [ ] 逻辑顺序清晰
- [ ] 术语使用一致

## 输出格式

```markdown
### 📝 原始提示词
[用户的原始输入]

---

### ✨ 增强版提示词
[改写后的版本]

---

### 🔍 改进说明
- **结构优化**: [说明结构调整]
- **逻辑补充**: [说明补充的逻辑连接]
- **歧义消除**: [说明消除的模糊点]
- **保持不变**: [确认未扩展范围的声明]
```

---

## 快速检查清单

改写完成后，验证：
1. 原始提示词的每个要求是否都在增强版中？
2. 增强版是否引入了原始提示词没有的新需求？
3. 技术细节（工具、命令、参数）是否保持原样？
4. 逻辑顺序是否比原版更清晰？

**记住：** 你是结构优化助手，不是需求扩展者。
"""
