export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  ".ts": "TypeScript",
  ".tsx": "TypeScript",
  ".js": "JavaScript",
  ".jsx": "JavaScript",
  ".py": "Python",
  ".rb": "Ruby",
  ".go": "Go",
  ".rs": "Rust",
  ".java": "Java",
  ".md": "Markdown",
  ".json": "JSON",
  ".yaml": "YAML",
  ".yml": "YAML",
  ".sh": "Shell",
  ".css": "CSS",
  ".html": "HTML",
}

export const LABEL_MAP: Record<string, string> = {
  debug_investigate: "Debug/Investigate",
  implement_feature: "Implement Feature",
  fix_bug: "Fix Bug",
  write_script_tool: "Write Script/Tool",
  refactor_code: "Refactor Code",
  configure_system: "Configure System",
  create_pr_commit: "Create PR/Commit",
  analyze_data: "Analyze Data",
  understand_codebase: "Understand Codebase",
  write_tests: "Write Tests",
  write_docs: "Write Docs",
  deploy_infra: "Deploy/Infra",
  warmup_minimal: "Cache Warmup",
  fast_accurate_search: "Fast/Accurate Search",
  correct_code_edits: "Correct Code Edits",
  good_explanations: "Good Explanations",
  proactive_help: "Proactive Help",
  multi_file_changes: "Multi-file Changes",
  handled_complexity: "Multi-file Changes",
  good_debugging: "Good Debugging",
  misunderstood_request: "Misunderstood Request",
  wrong_approach: "Wrong Approach",
  buggy_code: "Buggy Code",
  user_rejected_action: "User Rejected Action",
  claude_got_blocked: "Claude Got Blocked",
  user_stopped_early: "User Stopped Early",
  wrong_file_or_location: "Wrong File/Location",
  excessive_changes: "Excessive Changes",
  slow_or_verbose: "Slow/Verbose",
  tool_failed: "Tool Failed",
  user_unclear: "User Unclear",
  external_issue: "External Issue",
  frustrated: "Frustrated",
  dissatisfied: "Dissatisfied",
  likely_satisfied: "Likely Satisfied",
  satisfied: "Satisfied",
  happy: "Happy",
  unsure: "Unsure",
  neutral: "Neutral",
  delighted: "Delighted",
  single_task: "Single Task",
  multi_task: "Multi Task",
  iterative_refinement: "Iterative Refinement",
  exploration: "Exploration",
  quick_question: "Quick Question",
  fully_achieved: "Fully Achieved",
  mostly_achieved: "Mostly Achieved",
  partially_achieved: "Partially Achieved",
  not_achieved: "Not Achieved",
  unclear_from_transcript: "Unclear",
  unhelpful: "Unhelpful",
  slightly_helpful: "Slightly Helpful",
  moderately_helpful: "Moderately Helpful",
  very_helpful: "Very Helpful",
  essential: "Essential",
}

export const SATISFACTION_ORDER = [
  "frustrated",
  "dissatisfied",
  "likely_satisfied",
  "satisfied",
  "happy",
  "unsure",
  "neutral",
  "delighted",
]

export const OUTCOME_ORDER = [
  "not_achieved",
  "partially_achieved",
  "mostly_achieved",
  "fully_achieved",
  "unclear_from_transcript",
]

export const MAX_FACET_EXTRACTIONS = 50
export const CONCURRENCY = 50
export const MAX_SESSIONS = 200

export {}
